package com.dlut.dao;

import com.dlut.pojo.Cluster;
import com.dlut.pojo.ClusterExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface ClusterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    int countByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    int deleteByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    @Delete({
        "delete from cluster",
        "where cluster_id = #{clusterId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer clusterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    @Insert({
        "insert into cluster (cluster_id, cluster_name, ",
        "cluster_node_number, cluster_master_number, ",
        "cluster_slave_number, cluster_storage_number, ",
        "cluster_cpu_number, cluster_cpu_kernel_number, ",
        "cluster_total_storage, cluster_total_momery, ",
        "cluster_os)",
        "values (#{clusterId,jdbcType=INTEGER}, #{clusterName,jdbcType=VARCHAR}, ",
        "#{clusterNodeNumber,jdbcType=INTEGER}, #{clusterMasterNumber,jdbcType=INTEGER}, ",
        "#{clusterSlaveNumber,jdbcType=INTEGER}, #{clusterStorageNumber,jdbcType=INTEGER}, ",
        "#{clusterCpuNumber,jdbcType=INTEGER}, #{clusterCpuKernelNumber,jdbcType=INTEGER}, ",
        "#{clusterTotalStorage,jdbcType=VARCHAR}, #{clusterTotalMomery,jdbcType=VARCHAR}, ",
        "#{clusterOs,jdbcType=VARCHAR})"
    })
    int insert(Cluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    int insertSelective(Cluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    List<Cluster> selectByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "cluster_id, cluster_name, cluster_node_number, cluster_master_number, cluster_slave_number, ",
        "cluster_storage_number, cluster_cpu_number, cluster_cpu_kernel_number, cluster_total_storage, ",
        "cluster_total_momery, cluster_os",
        "from cluster",
        "where cluster_id = #{clusterId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Cluster selectByPrimaryKey(Integer clusterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Cluster record, @Param("example") ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Cluster record, @Param("example") ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    @Update({
        "update cluster",
        "set cluster_name = #{clusterName,jdbcType=VARCHAR},",
          "cluster_node_number = #{clusterNodeNumber,jdbcType=INTEGER},",
          "cluster_master_number = #{clusterMasterNumber,jdbcType=INTEGER},",
          "cluster_slave_number = #{clusterSlaveNumber,jdbcType=INTEGER},",
          "cluster_storage_number = #{clusterStorageNumber,jdbcType=INTEGER},",
          "cluster_cpu_number = #{clusterCpuNumber,jdbcType=INTEGER},",
          "cluster_cpu_kernel_number = #{clusterCpuKernelNumber,jdbcType=INTEGER},",
          "cluster_total_storage = #{clusterTotalStorage,jdbcType=VARCHAR},",
          "cluster_total_momery = #{clusterTotalMomery,jdbcType=VARCHAR},",
          "cluster_os = #{clusterOs,jdbcType=VARCHAR}",
        "where cluster_id = #{clusterId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Cluster record);
}