package com.dlut.dao;

import com.dlut.pojo.Inorganinc;
import com.dlut.pojo.InorganincExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface InorganincMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    int countByExample(InorganincExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    int deleteByExample(InorganincExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    @Delete({
        "delete from inorganinc",
        "where elemID = #{elemid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer elemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    @Insert({
        "insert into inorganinc (elemID, timeStemp, ",
        "data)",
        "values (#{elemid,jdbcType=INTEGER}, #{timestemp,jdbcType=CHAR}, ",
        "#{data,jdbcType=REAL})"
    })
    int insert(Inorganinc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    int insertSelective(Inorganinc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    List<Inorganinc> selectByExample(InorganincExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "elemID, timeStemp, data",
        "from inorganinc",
        "where elemID = #{elemid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Inorganinc selectByPrimaryKey(Integer elemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Inorganinc record, @Param("example") InorganincExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Inorganinc record, @Param("example") InorganincExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Inorganinc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    @Update({
        "update inorganinc",
        "set timeStemp = #{timestemp,jdbcType=CHAR},",
          "data = #{data,jdbcType=REAL}",
        "where elemID = #{elemid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Inorganinc record);
}