package com.dlut.dao;

import com.dlut.pojo.Metalelem;
import com.dlut.pojo.MetalelemExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MetalelemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    int countByExample(MetalelemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    int deleteByExample(MetalelemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    @Delete({
        "delete from metalelem",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    @Insert({
        "insert into metalelem (id, timeStamp, ",
        "elem1, elem2, elem3)",
        "values (#{id,jdbcType=INTEGER}, #{timestamp,jdbcType=VARCHAR}, ",
        "#{elem1,jdbcType=REAL}, #{elem2,jdbcType=REAL}, #{elem3,jdbcType=REAL})"
    })
    int insert(Metalelem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    int insertSelective(Metalelem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    List<Metalelem> selectByExample(MetalelemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, timeStamp, elem1, elem2, elem3",
        "from metalelem",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Metalelem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Metalelem record, @Param("example") MetalelemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Metalelem record, @Param("example") MetalelemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Metalelem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metalelem
     *
     * @mbggenerated
     */
    @Update({
        "update metalelem",
        "set timeStamp = #{timestamp,jdbcType=VARCHAR},",
          "elem1 = #{elem1,jdbcType=REAL},",
          "elem2 = #{elem2,jdbcType=REAL},",
          "elem3 = #{elem3,jdbcType=REAL}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Metalelem record);
}