package com.dlut.dao;

import com.dlut.pojo.Organic;
import com.dlut.pojo.OrganicExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OrganicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    int countByExample(OrganicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    int deleteByExample(OrganicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    @Delete({
        "delete from organic",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    @Insert({
        "insert into organic (id, organ1, ",
        "organ2, organ3)",
        "values (#{id,jdbcType=INTEGER}, #{organ1,jdbcType=REAL}, ",
        "#{organ2,jdbcType=REAL}, #{organ3,jdbcType=REAL})"
    })
    int insert(Organic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    int insertSelective(Organic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    List<Organic> selectByExample(OrganicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, organ1, organ2, organ3",
        "from organic",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Organic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Organic record, @Param("example") OrganicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Organic record, @Param("example") OrganicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Organic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    @Update({
        "update organic",
        "set organ1 = #{organ1,jdbcType=REAL},",
          "organ2 = #{organ2,jdbcType=REAL},",
          "organ3 = #{organ3,jdbcType=REAL}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Organic record);
}