package com.dlut.dao;

import com.dlut.pojo.Sourcetable;
import com.dlut.pojo.SourcetableExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SourcetableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    int countByExample(SourcetableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    int deleteByExample(SourcetableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sourcetable",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sourcetable (id, pollutionName, ",
        "Cr, Ni, Cu, ",
        "Zn, _As, Cd, ",
        "Hg, Pb, _describe)",
        "values (#{id,jdbcType=INTEGER}, #{pollutionname,jdbcType=VARCHAR}, ",
        "#{cr,jdbcType=INTEGER}, #{ni,jdbcType=INTEGER}, #{cu,jdbcType=INTEGER}, ",
        "#{zn,jdbcType=INTEGER}, #{as,jdbcType=INTEGER}, #{cd,jdbcType=INTEGER}, ",
        "#{hg,jdbcType=INTEGER}, #{pb,jdbcType=INTEGER}, #{describe,jdbcType=VARCHAR})"
    })
    int insert(Sourcetable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    int insertSelective(Sourcetable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    List<Sourcetable> selectByExample(SourcetableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, pollutionName, Cr, Ni, Cu, Zn, _As, Cd, Hg, Pb, _describe",
        "from sourcetable",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Sourcetable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Sourcetable record, @Param("example") SourcetableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Sourcetable record, @Param("example") SourcetableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sourcetable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    @Update({
        "update sourcetable",
        "set pollutionName = #{pollutionname,jdbcType=VARCHAR},",
          "Cr = #{cr,jdbcType=INTEGER},",
          "Ni = #{ni,jdbcType=INTEGER},",
          "Cu = #{cu,jdbcType=INTEGER},",
          "Zn = #{zn,jdbcType=INTEGER},",
          "_As = #{as,jdbcType=INTEGER},",
          "Cd = #{cd,jdbcType=INTEGER},",
          "Hg = #{hg,jdbcType=INTEGER},",
          "Pb = #{pb,jdbcType=INTEGER},",
          "_describe = #{describe,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Sourcetable record);
}