package com.dlut.dao;

import com.dlut.pojo.Userfile;
import com.dlut.pojo.UserfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    int countByExample(UserfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    int deleteByExample(UserfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    @Delete({
        "delete from userfile",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    @Insert({
        "insert into userfile (id, user_id, ",
        "user_name, algo_name, ",
        "file_name, file_format, ",
        "file_time, algo_id)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{userName,jdbcType=VARCHAR}, #{algoName,jdbcType=VARCHAR}, ",
        "#{fileName,jdbcType=VARCHAR}, #{fileFormat,jdbcType=VARCHAR}, ",
        "#{fileTime,jdbcType=VARCHAR}, #{algoId,jdbcType=INTEGER})"
    })
    int insert(Userfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    int insertSelective(Userfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    List<Userfile> selectByExample(UserfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, user_id, user_name, algo_name, file_name, file_format, file_time, algo_id",
        "from userfile",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Userfile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Userfile record, @Param("example") UserfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Userfile record, @Param("example") UserfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    @Update({
        "update userfile",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "algo_name = #{algoName,jdbcType=VARCHAR},",
          "file_name = #{fileName,jdbcType=VARCHAR},",
          "file_format = #{fileFormat,jdbcType=VARCHAR},",
          "file_time = #{fileTime,jdbcType=VARCHAR},",
          "algo_id = #{algoId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Userfile record);
}