package com.dlut.pojo;

import java.util.ArrayList;
import java.util.List;

public class AlgHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public AlgHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAlgIdIsNull() {
            addCriterion("alg_id is null");
            return (Criteria) this;
        }

        public Criteria andAlgIdIsNotNull() {
            addCriterion("alg_id is not null");
            return (Criteria) this;
        }

        public Criteria andAlgIdEqualTo(Integer value) {
            addCriterion("alg_id =", value, "algId");
            return (Criteria) this;
        }

        public Criteria andAlgIdNotEqualTo(Integer value) {
            addCriterion("alg_id <>", value, "algId");
            return (Criteria) this;
        }

        public Criteria andAlgIdGreaterThan(Integer value) {
            addCriterion("alg_id >", value, "algId");
            return (Criteria) this;
        }

        public Criteria andAlgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("alg_id >=", value, "algId");
            return (Criteria) this;
        }

        public Criteria andAlgIdLessThan(Integer value) {
            addCriterion("alg_id <", value, "algId");
            return (Criteria) this;
        }

        public Criteria andAlgIdLessThanOrEqualTo(Integer value) {
            addCriterion("alg_id <=", value, "algId");
            return (Criteria) this;
        }

        public Criteria andAlgIdIn(List<Integer> values) {
            addCriterion("alg_id in", values, "algId");
            return (Criteria) this;
        }

        public Criteria andAlgIdNotIn(List<Integer> values) {
            addCriterion("alg_id not in", values, "algId");
            return (Criteria) this;
        }

        public Criteria andAlgIdBetween(Integer value1, Integer value2) {
            addCriterion("alg_id between", value1, value2, "algId");
            return (Criteria) this;
        }

        public Criteria andAlgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("alg_id not between", value1, value2, "algId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andDataFileNameIsNull() {
            addCriterion("data_file_name is null");
            return (Criteria) this;
        }

        public Criteria andDataFileNameIsNotNull() {
            addCriterion("data_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andDataFileNameEqualTo(String value) {
            addCriterion("data_file_name =", value, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameNotEqualTo(String value) {
            addCriterion("data_file_name <>", value, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameGreaterThan(String value) {
            addCriterion("data_file_name >", value, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("data_file_name >=", value, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameLessThan(String value) {
            addCriterion("data_file_name <", value, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameLessThanOrEqualTo(String value) {
            addCriterion("data_file_name <=", value, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameLike(String value) {
            addCriterion("data_file_name like", value, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameNotLike(String value) {
            addCriterion("data_file_name not like", value, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameIn(List<String> values) {
            addCriterion("data_file_name in", values, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameNotIn(List<String> values) {
            addCriterion("data_file_name not in", values, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameBetween(String value1, String value2) {
            addCriterion("data_file_name between", value1, value2, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFileNameNotBetween(String value1, String value2) {
            addCriterion("data_file_name not between", value1, value2, "dataFileName");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeIsNull() {
            addCriterion("data_flle_type is null");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeIsNotNull() {
            addCriterion("data_flle_type is not null");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeEqualTo(String value) {
            addCriterion("data_flle_type =", value, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeNotEqualTo(String value) {
            addCriterion("data_flle_type <>", value, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeGreaterThan(String value) {
            addCriterion("data_flle_type >", value, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("data_flle_type >=", value, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeLessThan(String value) {
            addCriterion("data_flle_type <", value, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeLessThanOrEqualTo(String value) {
            addCriterion("data_flle_type <=", value, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeLike(String value) {
            addCriterion("data_flle_type like", value, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeNotLike(String value) {
            addCriterion("data_flle_type not like", value, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeIn(List<String> values) {
            addCriterion("data_flle_type in", values, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeNotIn(List<String> values) {
            addCriterion("data_flle_type not in", values, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeBetween(String value1, String value2) {
            addCriterion("data_flle_type between", value1, value2, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andDataFlleTypeNotBetween(String value1, String value2) {
            addCriterion("data_flle_type not between", value1, value2, "dataFlleType");
            return (Criteria) this;
        }

        public Criteria andExecTimeIsNull() {
            addCriterion("exec_time is null");
            return (Criteria) this;
        }

        public Criteria andExecTimeIsNotNull() {
            addCriterion("exec_time is not null");
            return (Criteria) this;
        }

        public Criteria andExecTimeEqualTo(String value) {
            addCriterion("exec_time =", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotEqualTo(String value) {
            addCriterion("exec_time <>", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeGreaterThan(String value) {
            addCriterion("exec_time >", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeGreaterThanOrEqualTo(String value) {
            addCriterion("exec_time >=", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeLessThan(String value) {
            addCriterion("exec_time <", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeLessThanOrEqualTo(String value) {
            addCriterion("exec_time <=", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeLike(String value) {
            addCriterion("exec_time like", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotLike(String value) {
            addCriterion("exec_time not like", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeIn(List<String> values) {
            addCriterion("exec_time in", values, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotIn(List<String> values) {
            addCriterion("exec_time not in", values, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeBetween(String value1, String value2) {
            addCriterion("exec_time between", value1, value2, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotBetween(String value1, String value2) {
            addCriterion("exec_time not between", value1, value2, "execTime");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameIsNull() {
            addCriterion("reslut_dir_name is null");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameIsNotNull() {
            addCriterion("reslut_dir_name is not null");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameEqualTo(String value) {
            addCriterion("reslut_dir_name =", value, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameNotEqualTo(String value) {
            addCriterion("reslut_dir_name <>", value, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameGreaterThan(String value) {
            addCriterion("reslut_dir_name >", value, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameGreaterThanOrEqualTo(String value) {
            addCriterion("reslut_dir_name >=", value, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameLessThan(String value) {
            addCriterion("reslut_dir_name <", value, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameLessThanOrEqualTo(String value) {
            addCriterion("reslut_dir_name <=", value, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameLike(String value) {
            addCriterion("reslut_dir_name like", value, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameNotLike(String value) {
            addCriterion("reslut_dir_name not like", value, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameIn(List<String> values) {
            addCriterion("reslut_dir_name in", values, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameNotIn(List<String> values) {
            addCriterion("reslut_dir_name not in", values, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameBetween(String value1, String value2) {
            addCriterion("reslut_dir_name between", value1, value2, "reslutDirName");
            return (Criteria) this;
        }

        public Criteria andReslutDirNameNotBetween(String value1, String value2) {
            addCriterion("reslut_dir_name not between", value1, value2, "reslutDirName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alg_history
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}