package com.dlut.pojo;

public class AlgHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alg_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alg_history.alg_id
     *
     * @mbggenerated
     */
    private Integer algId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alg_history.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alg_history.data_file_name
     *
     * @mbggenerated
     */
    private String dataFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alg_history.data_flle_type
     *
     * @mbggenerated
     */
    private String dataFlleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alg_history.exec_time
     *
     * @mbggenerated
     */
    private String execTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alg_history.reslut_dir_name
     *
     * @mbggenerated
     */
    private String reslutDirName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alg_history
     *
     * @mbggenerated
     */
    public AlgHistory(Integer id, Integer algId, Integer userId, String dataFileName, String dataFlleType, String execTime, String reslutDirName) {
        this.id = id;
        this.algId = algId;
        this.userId = userId;
        this.dataFileName = dataFileName;
        this.dataFlleType = dataFlleType;
        this.execTime = execTime;
        this.reslutDirName = reslutDirName;
    }

    public AlgHistory(Integer algId, Integer userId, String dataFileName, String dataFlleType, String execTime, String reslutDirName) {

        this.algId = algId;
        this.userId = userId;
        this.dataFileName = dataFileName;
        this.dataFlleType = dataFlleType;
        this.execTime = execTime;
        this.reslutDirName = reslutDirName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alg_history.id
     *
     * @return the value of alg_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alg_history.alg_id
     *
     * @return the value of alg_history.alg_id
     *
     * @mbggenerated
     */
    public Integer getAlgId() {
        return algId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alg_history.user_id
     *
     * @return the value of alg_history.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alg_history.data_file_name
     *
     * @return the value of alg_history.data_file_name
     *
     * @mbggenerated
     */
    public String getDataFileName() {
        return dataFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alg_history.data_flle_type
     *
     * @return the value of alg_history.data_flle_type
     *
     * @mbggenerated
     */
    public String getDataFlleType() {
        return dataFlleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alg_history.exec_time
     *
     * @return the value of alg_history.exec_time
     *
     * @mbggenerated
     */
    public String getExecTime() {
        return execTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alg_history.reslut_dir_name
     *
     * @return the value of alg_history.reslut_dir_name
     *
     * @mbggenerated
     */
    public String getReslutDirName() {
        return reslutDirName;
    }
}