package com.dlut.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlgorithmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public AlgorithmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAlgorithmIdIsNull() {
            addCriterion("algorithm_id is null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdIsNotNull() {
            addCriterion("algorithm_id is not null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdEqualTo(Integer value) {
            addCriterion("algorithm_id =", value, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdNotEqualTo(Integer value) {
            addCriterion("algorithm_id <>", value, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdGreaterThan(Integer value) {
            addCriterion("algorithm_id >", value, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("algorithm_id >=", value, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdLessThan(Integer value) {
            addCriterion("algorithm_id <", value, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdLessThanOrEqualTo(Integer value) {
            addCriterion("algorithm_id <=", value, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdIn(List<Integer> values) {
            addCriterion("algorithm_id in", values, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdNotIn(List<Integer> values) {
            addCriterion("algorithm_id not in", values, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdBetween(Integer value1, Integer value2) {
            addCriterion("algorithm_id between", value1, value2, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("algorithm_id not between", value1, value2, "algorithmId");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameIsNull() {
            addCriterion("algorithm_name is null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameIsNotNull() {
            addCriterion("algorithm_name is not null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameEqualTo(String value) {
            addCriterion("algorithm_name =", value, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameNotEqualTo(String value) {
            addCriterion("algorithm_name <>", value, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameGreaterThan(String value) {
            addCriterion("algorithm_name >", value, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameGreaterThanOrEqualTo(String value) {
            addCriterion("algorithm_name >=", value, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameLessThan(String value) {
            addCriterion("algorithm_name <", value, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameLessThanOrEqualTo(String value) {
            addCriterion("algorithm_name <=", value, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameLike(String value) {
            addCriterion("algorithm_name like", value, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameNotLike(String value) {
            addCriterion("algorithm_name not like", value, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameIn(List<String> values) {
            addCriterion("algorithm_name in", values, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameNotIn(List<String> values) {
            addCriterion("algorithm_name not in", values, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameBetween(String value1, String value2) {
            addCriterion("algorithm_name between", value1, value2, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmNameNotBetween(String value1, String value2) {
            addCriterion("algorithm_name not between", value1, value2, "algorithmName");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdIsNull() {
            addCriterion("algorithm_cmd is null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdIsNotNull() {
            addCriterion("algorithm_cmd is not null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdEqualTo(String value) {
            addCriterion("algorithm_cmd =", value, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdNotEqualTo(String value) {
            addCriterion("algorithm_cmd <>", value, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdGreaterThan(String value) {
            addCriterion("algorithm_cmd >", value, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdGreaterThanOrEqualTo(String value) {
            addCriterion("algorithm_cmd >=", value, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdLessThan(String value) {
            addCriterion("algorithm_cmd <", value, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdLessThanOrEqualTo(String value) {
            addCriterion("algorithm_cmd <=", value, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdLike(String value) {
            addCriterion("algorithm_cmd like", value, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdNotLike(String value) {
            addCriterion("algorithm_cmd not like", value, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdIn(List<String> values) {
            addCriterion("algorithm_cmd in", values, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdNotIn(List<String> values) {
            addCriterion("algorithm_cmd not in", values, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdBetween(String value1, String value2) {
            addCriterion("algorithm_cmd between", value1, value2, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmCmdNotBetween(String value1, String value2) {
            addCriterion("algorithm_cmd not between", value1, value2, "algorithmCmd");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorIsNull() {
            addCriterion("algorithm_author is null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorIsNotNull() {
            addCriterion("algorithm_author is not null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorEqualTo(String value) {
            addCriterion("algorithm_author =", value, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorNotEqualTo(String value) {
            addCriterion("algorithm_author <>", value, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorGreaterThan(String value) {
            addCriterion("algorithm_author >", value, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("algorithm_author >=", value, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorLessThan(String value) {
            addCriterion("algorithm_author <", value, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorLessThanOrEqualTo(String value) {
            addCriterion("algorithm_author <=", value, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorLike(String value) {
            addCriterion("algorithm_author like", value, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorNotLike(String value) {
            addCriterion("algorithm_author not like", value, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorIn(List<String> values) {
            addCriterion("algorithm_author in", values, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorNotIn(List<String> values) {
            addCriterion("algorithm_author not in", values, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorBetween(String value1, String value2) {
            addCriterion("algorithm_author between", value1, value2, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmAuthorNotBetween(String value1, String value2) {
            addCriterion("algorithm_author not between", value1, value2, "algorithmAuthor");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeIsNull() {
            addCriterion("algorithm_time is null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeIsNotNull() {
            addCriterion("algorithm_time is not null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeEqualTo(Date value) {
            addCriterion("algorithm_time =", value, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeNotEqualTo(Date value) {
            addCriterion("algorithm_time <>", value, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeGreaterThan(Date value) {
            addCriterion("algorithm_time >", value, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("algorithm_time >=", value, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeLessThan(Date value) {
            addCriterion("algorithm_time <", value, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeLessThanOrEqualTo(Date value) {
            addCriterion("algorithm_time <=", value, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeIn(List<Date> values) {
            addCriterion("algorithm_time in", values, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeNotIn(List<Date> values) {
            addCriterion("algorithm_time not in", values, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeBetween(Date value1, Date value2) {
            addCriterion("algorithm_time between", value1, value2, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTimeNotBetween(Date value1, Date value2) {
            addCriterion("algorithm_time not between", value1, value2, "algorithmTime");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Integer value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Integer value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Integer value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Integer value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Integer> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Integer> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Integer value1, Integer value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("class_name is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("class_name is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("class_name =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("class_name <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("class_name >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_name >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("class_name <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("class_name <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("class_name like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("class_name not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("class_name in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("class_name not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("class_name between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("class_name not between", value1, value2, "className");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table algorithm
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}