package com.dlut.pojo;

import java.io.Serializable;
import java.util.Date;

public class AlgorithmWithBLOBs extends Algorithm implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm.algorithm_describe
     *
     * @mbggenerated
     */
    private String algorithmDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm.algorithm_tip
     *
     * @mbggenerated
     */
    private String algorithmTip;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */

    public AlgorithmWithBLOBs(){

    }

    public AlgorithmWithBLOBs(Integer algorithmId, String algorithmName, String algorithmCmd, String algorithmAuthor, Date algorithmTime, Integer classId, String className, String algorithmDescribe, String algorithmTip) {
        super(algorithmId, algorithmName, algorithmCmd, algorithmAuthor, algorithmTime, classId, className);
        this.algorithmDescribe = algorithmDescribe;
        this.algorithmTip = algorithmTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm.algorithm_describe
     *
     * @return the value of algorithm.algorithm_describe
     *
     * @mbggenerated
     */
    public String getAlgorithmDescribe() {
        return algorithmDescribe;
    }

    public void setAlgorithmDescribe(String describe){
        this.algorithmDescribe = describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm.algorithm_tip
     *
     * @return the value of algorithm.algorithm_tip
     *
     * @mbggenerated
     */
    public String getAlgorithmTip() {
        return algorithmTip;
    }

    public void setAlgorithmTip(String tip){
        this.algorithmTip = tip;
    }

    @Override
    public String toString() {
        return super.toString()+"AlgorithmWithBLOBs{" +
                "algorithmDescribe='" + algorithmDescribe + '\'' +
                ", algorithmTip='" + algorithmTip + '\'' +
                '}';
    }
}