package com.dlut.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Algorithm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm.algorithm_id
     *
     * @mbggenerated
     */
    private Integer algorithmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm.algorithm_name
     *
     * @mbggenerated
     */
    private String algorithmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm.algorithm_cmd
     *
     * @mbggenerated
     */
    private String algorithmCmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm.algorithm_author
     *
     * @mbggenerated
     */
    private String algorithmAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm.algorithm_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date algorithmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm.class_id
     *
     * @mbggenerated
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm.class_name
     *
     * @mbggenerated
     */
    private String className;


    public Algorithm(){
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm
     *
     * @mbggenerated
     */
    public Algorithm(Integer algorithmId, String algorithmName, String algorithmCmd, String algorithmAuthor, Date algorithmTime, Integer classId, String className) {
        this.algorithmId = algorithmId;
        this.algorithmName = algorithmName;
        this.algorithmCmd = algorithmCmd;
        this.algorithmAuthor = algorithmAuthor;
        this.algorithmTime = algorithmTime;
        this.classId = classId;
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm.algorithm_id
     *
     * @return the value of algorithm.algorithm_id
     *
     * @mbggenerated
     */
    public Integer getAlgorithmId() {
        return algorithmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm.algorithm_name
     *
     * @return the value of algorithm.algorithm_name
     *
     * @mbggenerated
     */
    public String getAlgorithmName() {
        return algorithmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm.algorithm_cmd
     *
     * @return the value of algorithm.algorithm_cmd
     *
     * @mbggenerated
     */
    public String getAlgorithmCmd() {
        return algorithmCmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm.algorithm_author
     *
     * @return the value of algorithm.algorithm_author
     *
     * @mbggenerated
     */
    public String getAlgorithmAuthor() {
        return algorithmAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm.algorithm_time
     *
     * @return the value of algorithm.algorithm_time
     *
     * @mbggenerated
     */
    public Date getAlgorithmTime() {
        return algorithmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm.class_id
     *
     * @return the value of algorithm.class_id
     *
     * @mbggenerated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm.class_name
     *
     * @return the value of algorithm.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    public void setAlgorithmAuthor(String algorithmAuthor) {
        this.algorithmAuthor = algorithmAuthor;
    }

    public void setAlgorithmTime(Date algorithmTime) {
        this.algorithmTime = algorithmTime;
    }

    @Override
    public String toString() {
        return "Algorithm{" +
                "algorithmId=" + algorithmId +
                ", algorithmName='" + algorithmName + '\'' +
                ", algorithmCmd='" + algorithmCmd + '\'' +
                ", algorithmAuthor='" + algorithmAuthor + '\'' +
                ", algorithmTime=" + algorithmTime +
                ", classId=" + classId +
                ", className='" + className + '\'' +
                '}';
    }
}