package com.dlut.pojo;

/**
 * Created by zhonghua on 2016/7/18.
 */
public class ClassNumber extends Class {

    private Integer classNumber;

    public ClassNumber(){
        super();
    }

    public ClassNumber(Integer classId, String className,Integer classType, String classDescribe, Integer classNumber) {
        super(classId, className,classType, classDescribe);
        this.classNumber = classNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @param classId
     * @param className
     * @param classDescribe
     * @mbggenerated
     */
    public ClassNumber(Integer classId, String className,Integer classType, String classDescribe) {
        super(classId, className,classType, classDescribe);
    }



    public int getClassNumber() {
        return classNumber;
    }

    public void setClassNumber(Integer classNumber) {
        this.classNumber = classNumber;
    }

    @Override
    public String toString() {
        return "ClassNumber{" +
                super.toString()+
                "classNumber=" + classNumber +
                '}';
    }
}
