package com.dlut.pojo;

public class Cluster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_id
     *
     * @mbggenerated
     */
    private Integer clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_name
     *
     * @mbggenerated
     */
    private String clusterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_node_number
     *
     * @mbggenerated
     */
    private Integer clusterNodeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_master_number
     *
     * @mbggenerated
     */
    private Integer clusterMasterNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_slave_number
     *
     * @mbggenerated
     */
    private Integer clusterSlaveNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_storage_number
     *
     * @mbggenerated
     */
    private Integer clusterStorageNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_cpu_number
     *
     * @mbggenerated
     */
    private Integer clusterCpuNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_cpu_kernel_number
     *
     * @mbggenerated
     */
    private Integer clusterCpuKernelNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_total_storage
     *
     * @mbggenerated
     */
    private String clusterTotalStorage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_total_momery
     *
     * @mbggenerated
     */
    private String clusterTotalMomery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster.cluster_os
     *
     * @mbggenerated
     */
    private String clusterOs;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster
     *
     * @mbggenerated
     */
    public Cluster(Integer clusterId, String clusterName, Integer clusterNodeNumber, Integer clusterMasterNumber, Integer clusterSlaveNumber, Integer clusterStorageNumber, Integer clusterCpuNumber, Integer clusterCpuKernelNumber, String clusterTotalStorage, String clusterTotalMomery, String clusterOs) {
        this.clusterId = clusterId;
        this.clusterName = clusterName;
        this.clusterNodeNumber = clusterNodeNumber;
        this.clusterMasterNumber = clusterMasterNumber;
        this.clusterSlaveNumber = clusterSlaveNumber;
        this.clusterStorageNumber = clusterStorageNumber;
        this.clusterCpuNumber = clusterCpuNumber;
        this.clusterCpuKernelNumber = clusterCpuKernelNumber;
        this.clusterTotalStorage = clusterTotalStorage;
        this.clusterTotalMomery = clusterTotalMomery;
        this.clusterOs = clusterOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_id
     *
     * @return the value of cluster.cluster_id
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_name
     *
     * @return the value of cluster.cluster_name
     *
     * @mbggenerated
     */
    public String getClusterName() {
        return clusterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_node_number
     *
     * @return the value of cluster.cluster_node_number
     *
     * @mbggenerated
     */
    public Integer getClusterNodeNumber() {
        return clusterNodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_master_number
     *
     * @return the value of cluster.cluster_master_number
     *
     * @mbggenerated
     */
    public Integer getClusterMasterNumber() {
        return clusterMasterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_slave_number
     *
     * @return the value of cluster.cluster_slave_number
     *
     * @mbggenerated
     */
    public Integer getClusterSlaveNumber() {
        return clusterSlaveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_storage_number
     *
     * @return the value of cluster.cluster_storage_number
     *
     * @mbggenerated
     */
    public Integer getClusterStorageNumber() {
        return clusterStorageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_cpu_number
     *
     * @return the value of cluster.cluster_cpu_number
     *
     * @mbggenerated
     */
    public Integer getClusterCpuNumber() {
        return clusterCpuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_cpu_kernel_number
     *
     * @return the value of cluster.cluster_cpu_kernel_number
     *
     * @mbggenerated
     */
    public Integer getClusterCpuKernelNumber() {
        return clusterCpuKernelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_total_storage
     *
     * @return the value of cluster.cluster_total_storage
     *
     * @mbggenerated
     */
    public String getClusterTotalStorage() {
        return clusterTotalStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_total_momery
     *
     * @return the value of cluster.cluster_total_momery
     *
     * @mbggenerated
     */
    public String getClusterTotalMomery() {
        return clusterTotalMomery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster.cluster_os
     *
     * @return the value of cluster.cluster_os
     *
     * @mbggenerated
     */
    public String getClusterOs() {
        return clusterOs;
    }
}