package com.dlut.pojo;

import java.util.ArrayList;
import java.util.List;

public class InorganincExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public InorganincExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andElemidIsNull() {
            addCriterion("elemID is null");
            return (Criteria) this;
        }

        public Criteria andElemidIsNotNull() {
            addCriterion("elemID is not null");
            return (Criteria) this;
        }

        public Criteria andElemidEqualTo(Integer value) {
            addCriterion("elemID =", value, "elemid");
            return (Criteria) this;
        }

        public Criteria andElemidNotEqualTo(Integer value) {
            addCriterion("elemID <>", value, "elemid");
            return (Criteria) this;
        }

        public Criteria andElemidGreaterThan(Integer value) {
            addCriterion("elemID >", value, "elemid");
            return (Criteria) this;
        }

        public Criteria andElemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("elemID >=", value, "elemid");
            return (Criteria) this;
        }

        public Criteria andElemidLessThan(Integer value) {
            addCriterion("elemID <", value, "elemid");
            return (Criteria) this;
        }

        public Criteria andElemidLessThanOrEqualTo(Integer value) {
            addCriterion("elemID <=", value, "elemid");
            return (Criteria) this;
        }

        public Criteria andElemidIn(List<Integer> values) {
            addCriterion("elemID in", values, "elemid");
            return (Criteria) this;
        }

        public Criteria andElemidNotIn(List<Integer> values) {
            addCriterion("elemID not in", values, "elemid");
            return (Criteria) this;
        }

        public Criteria andElemidBetween(Integer value1, Integer value2) {
            addCriterion("elemID between", value1, value2, "elemid");
            return (Criteria) this;
        }

        public Criteria andElemidNotBetween(Integer value1, Integer value2) {
            addCriterion("elemID not between", value1, value2, "elemid");
            return (Criteria) this;
        }

        public Criteria andTimestempIsNull() {
            addCriterion("timeStemp is null");
            return (Criteria) this;
        }

        public Criteria andTimestempIsNotNull() {
            addCriterion("timeStemp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestempEqualTo(String value) {
            addCriterion("timeStemp =", value, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempNotEqualTo(String value) {
            addCriterion("timeStemp <>", value, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempGreaterThan(String value) {
            addCriterion("timeStemp >", value, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempGreaterThanOrEqualTo(String value) {
            addCriterion("timeStemp >=", value, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempLessThan(String value) {
            addCriterion("timeStemp <", value, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempLessThanOrEqualTo(String value) {
            addCriterion("timeStemp <=", value, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempLike(String value) {
            addCriterion("timeStemp like", value, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempNotLike(String value) {
            addCriterion("timeStemp not like", value, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempIn(List<String> values) {
            addCriterion("timeStemp in", values, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempNotIn(List<String> values) {
            addCriterion("timeStemp not in", values, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempBetween(String value1, String value2) {
            addCriterion("timeStemp between", value1, value2, "timestemp");
            return (Criteria) this;
        }

        public Criteria andTimestempNotBetween(String value1, String value2) {
            addCriterion("timeStemp not between", value1, value2, "timestemp");
            return (Criteria) this;
        }

        public Criteria andDataIsNull() {
            addCriterion("data is null");
            return (Criteria) this;
        }

        public Criteria andDataIsNotNull() {
            addCriterion("data is not null");
            return (Criteria) this;
        }

        public Criteria andDataEqualTo(Float value) {
            addCriterion("data =", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotEqualTo(Float value) {
            addCriterion("data <>", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThan(Float value) {
            addCriterion("data >", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThanOrEqualTo(Float value) {
            addCriterion("data >=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThan(Float value) {
            addCriterion("data <", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThanOrEqualTo(Float value) {
            addCriterion("data <=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataIn(List<Float> values) {
            addCriterion("data in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotIn(List<Float> values) {
            addCriterion("data not in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataBetween(Float value1, Float value2) {
            addCriterion("data between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotBetween(Float value1, Float value2) {
            addCriterion("data not between", value1, value2, "data");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inorganinc
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inorganinc
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}