package com.dlut.pojo;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_id
     *
     * @mbggenerated
     */
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_content
     *
     * @mbggenerated
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_time
     *
     * @mbggenerated
     */
    private Date messageTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    public Message(Integer messageId, String messageContent, Date messageTime, Integer userId) {
        this.messageId = messageId;
        this.messageContent = messageContent;
        this.messageTime = messageTime;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_id
     *
     * @return the value of message.message_id
     *
     * @mbggenerated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_content
     *
     * @return the value of message.message_content
     *
     * @mbggenerated
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_time
     *
     * @return the value of message.message_time
     *
     * @mbggenerated
     */
    public Date getMessageTime() {
        return messageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_id
     *
     * @return the value of message.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }
}