package com.dlut.pojo;

import java.util.Date;

public class Node {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_id
     *
     * @mbggenerated
     */
    private Integer nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_name
     *
     * @mbggenerated
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_status
     *
     * @mbggenerated
     */
    private String nodeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_ip
     *
     * @mbggenerated
     */
    private String nodeIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_specification
     *
     * @mbggenerated
     */
    private String nodeSpecification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_role
     *
     * @mbggenerated
     */
    private String nodeRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_creater
     *
     * @mbggenerated
     */
    private String nodeCreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_time
     *
     * @mbggenerated
     */
    private Date nodeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbggenerated
     */
    public Node(Integer nodeId, String nodeName, String nodeStatus, String nodeIp, String nodeSpecification, String nodeRole, String nodeCreater, Date nodeTime, String password) {
        this.nodeId = nodeId;
        this.nodeName = nodeName;
        this.nodeStatus = nodeStatus;
        this.nodeIp = nodeIp;
        this.nodeSpecification = nodeSpecification;
        this.nodeRole = nodeRole;
        this.nodeCreater = nodeCreater;
        this.nodeTime = nodeTime;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_id
     *
     * @return the value of node.node_id
     *
     * @mbggenerated
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_name
     *
     * @return the value of node.node_name
     *
     * @mbggenerated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_status
     *
     * @return the value of node.node_status
     *
     * @mbggenerated
     */
    public String getNodeStatus() {
        return nodeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_ip
     *
     * @return the value of node.node_ip
     *
     * @mbggenerated
     */
    public String getNodeIp() {
        return nodeIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_specification
     *
     * @return the value of node.node_specification
     *
     * @mbggenerated
     */
    public String getNodeSpecification() {
        return nodeSpecification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_role
     *
     * @return the value of node.node_role
     *
     * @mbggenerated
     */
    public String getNodeRole() {
        return nodeRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_creater
     *
     * @return the value of node.node_creater
     *
     * @mbggenerated
     */
    public String getNodeCreater() {
        return nodeCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_time
     *
     * @return the value of node.node_time
     *
     * @mbggenerated
     */
    public Date getNodeTime() {
        return nodeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.password
     *
     * @return the value of node.password
     *
     * @mbggenerated

     */
    public String getPassword() {
        return password;
    }

    public void setNodeStatus(String nodeStatus) {
        this.nodeStatus = nodeStatus;
    }
}