package com.dlut.pojo;

import java.util.ArrayList;
import java.util.List;

public class OrganicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organic
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organic
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organic
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public OrganicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organic
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table organic
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrgan1IsNull() {
            addCriterion("organ1 is null");
            return (Criteria) this;
        }

        public Criteria andOrgan1IsNotNull() {
            addCriterion("organ1 is not null");
            return (Criteria) this;
        }

        public Criteria andOrgan1EqualTo(Float value) {
            addCriterion("organ1 =", value, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan1NotEqualTo(Float value) {
            addCriterion("organ1 <>", value, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan1GreaterThan(Float value) {
            addCriterion("organ1 >", value, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan1GreaterThanOrEqualTo(Float value) {
            addCriterion("organ1 >=", value, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan1LessThan(Float value) {
            addCriterion("organ1 <", value, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan1LessThanOrEqualTo(Float value) {
            addCriterion("organ1 <=", value, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan1In(List<Float> values) {
            addCriterion("organ1 in", values, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan1NotIn(List<Float> values) {
            addCriterion("organ1 not in", values, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan1Between(Float value1, Float value2) {
            addCriterion("organ1 between", value1, value2, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan1NotBetween(Float value1, Float value2) {
            addCriterion("organ1 not between", value1, value2, "organ1");
            return (Criteria) this;
        }

        public Criteria andOrgan2IsNull() {
            addCriterion("organ2 is null");
            return (Criteria) this;
        }

        public Criteria andOrgan2IsNotNull() {
            addCriterion("organ2 is not null");
            return (Criteria) this;
        }

        public Criteria andOrgan2EqualTo(Float value) {
            addCriterion("organ2 =", value, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan2NotEqualTo(Float value) {
            addCriterion("organ2 <>", value, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan2GreaterThan(Float value) {
            addCriterion("organ2 >", value, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan2GreaterThanOrEqualTo(Float value) {
            addCriterion("organ2 >=", value, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan2LessThan(Float value) {
            addCriterion("organ2 <", value, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan2LessThanOrEqualTo(Float value) {
            addCriterion("organ2 <=", value, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan2In(List<Float> values) {
            addCriterion("organ2 in", values, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan2NotIn(List<Float> values) {
            addCriterion("organ2 not in", values, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan2Between(Float value1, Float value2) {
            addCriterion("organ2 between", value1, value2, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan2NotBetween(Float value1, Float value2) {
            addCriterion("organ2 not between", value1, value2, "organ2");
            return (Criteria) this;
        }

        public Criteria andOrgan3IsNull() {
            addCriterion("organ3 is null");
            return (Criteria) this;
        }

        public Criteria andOrgan3IsNotNull() {
            addCriterion("organ3 is not null");
            return (Criteria) this;
        }

        public Criteria andOrgan3EqualTo(Float value) {
            addCriterion("organ3 =", value, "organ3");
            return (Criteria) this;
        }

        public Criteria andOrgan3NotEqualTo(Float value) {
            addCriterion("organ3 <>", value, "organ3");
            return (Criteria) this;
        }

        public Criteria andOrgan3GreaterThan(Float value) {
            addCriterion("organ3 >", value, "organ3");
            return (Criteria) this;
        }

        public Criteria andOrgan3GreaterThanOrEqualTo(Float value) {
            addCriterion("organ3 >=", value, "organ3");
            return (Criteria) this;
        }

        public Criteria andOrgan3LessThan(Float value) {
            addCriterion("organ3 <", value, "organ3");
            return (Criteria) this;
        }

        public Criteria andOrgan3LessThanOrEqualTo(Float value) {
            addCriterion("organ3 <=", value, "organ3");
            return (Criteria) this;
        }

        public Criteria andOrgan3In(List<Float> values) {
            addCriterion("organ3 in", values, "organ3");
            return (Criteria) this;
        }

        public Criteria andOrgan3NotIn(List<Float> values) {
            addCriterion("organ3 not in", values, "organ3");
            return (Criteria) this;
        }

        public Criteria andOrgan3Between(Float value1, Float value2) {
            addCriterion("organ3 between", value1, value2, "organ3");
            return (Criteria) this;
        }

        public Criteria andOrgan3NotBetween(Float value1, Float value2) {
            addCriterion("organ3 not between", value1, value2, "organ3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table organic
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table organic
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}