package com.dlut.pojo;

public class Pollutionstandard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.ph_low
     *
     * @mbggenerated
     */
    private Float phLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.ph_high
     *
     * @mbggenerated
     */
    private Float phHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.Cr
     *
     * @mbggenerated
     */
    private Float cr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.Ni
     *
     * @mbggenerated
     */
    private Float ni;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.Cu
     *
     * @mbggenerated
     */
    private Float cu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.Zn
     *
     * @mbggenerated
     */
    private Float zn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard._As
     *
     * @mbggenerated
     */
    private Float as;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.Cd
     *
     * @mbggenerated
     */
    private Float cd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.Hg
     *
     * @mbggenerated
     */
    private Float hg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutionstandard.Pb
     *
     * @mbggenerated
     */
    private Float pb;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public Pollutionstandard(Integer id, Float phLow, Float phHigh, Float cr, Float ni, Float cu, Float zn, Float as, Float cd, Float hg, Float pb) {
        this.id = id;
        this.phLow = phLow;
        this.phHigh = phHigh;
        this.cr = cr;
        this.ni = ni;
        this.cu = cu;
        this.zn = zn;
        this.as = as;
        this.cd = cd;
        this.hg = hg;
        this.pb = pb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.id
     *
     * @return the value of pollutionstandard.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.ph_low
     *
     * @return the value of pollutionstandard.ph_low
     *
     * @mbggenerated
     */
    public Float getPhLow() {
        return phLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.ph_high
     *
     * @return the value of pollutionstandard.ph_high
     *
     * @mbggenerated
     */
    public Float getPhHigh() {
        return phHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.Cr
     *
     * @return the value of pollutionstandard.Cr
     *
     * @mbggenerated
     */
    public Float getCr() {
        return cr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.Ni
     *
     * @return the value of pollutionstandard.Ni
     *
     * @mbggenerated
     */
    public Float getNi() {
        return ni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.Cu
     *
     * @return the value of pollutionstandard.Cu
     *
     * @mbggenerated
     */
    public Float getCu() {
        return cu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.Zn
     *
     * @return the value of pollutionstandard.Zn
     *
     * @mbggenerated
     */
    public Float getZn() {
        return zn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard._As
     *
     * @return the value of pollutionstandard._As
     *
     * @mbggenerated
     */
    public Float getAs() {
        return as;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.Cd
     *
     * @return the value of pollutionstandard.Cd
     *
     * @mbggenerated
     */
    public Float getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.Hg
     *
     * @return the value of pollutionstandard.Hg
     *
     * @mbggenerated
     */
    public Float getHg() {
        return hg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutionstandard.Pb
     *
     * @return the value of pollutionstandard.Pb
     *
     * @mbggenerated
     */
    public Float getPb() {
        return pb;
    }
}