package com.dlut.pojo;

import java.util.ArrayList;
import java.util.List;

public class PollutionstandardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public PollutionstandardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPhLowIsNull() {
            addCriterion("ph_low is null");
            return (Criteria) this;
        }

        public Criteria andPhLowIsNotNull() {
            addCriterion("ph_low is not null");
            return (Criteria) this;
        }

        public Criteria andPhLowEqualTo(Float value) {
            addCriterion("ph_low =", value, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhLowNotEqualTo(Float value) {
            addCriterion("ph_low <>", value, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhLowGreaterThan(Float value) {
            addCriterion("ph_low >", value, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhLowGreaterThanOrEqualTo(Float value) {
            addCriterion("ph_low >=", value, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhLowLessThan(Float value) {
            addCriterion("ph_low <", value, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhLowLessThanOrEqualTo(Float value) {
            addCriterion("ph_low <=", value, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhLowIn(List<Float> values) {
            addCriterion("ph_low in", values, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhLowNotIn(List<Float> values) {
            addCriterion("ph_low not in", values, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhLowBetween(Float value1, Float value2) {
            addCriterion("ph_low between", value1, value2, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhLowNotBetween(Float value1, Float value2) {
            addCriterion("ph_low not between", value1, value2, "phLow");
            return (Criteria) this;
        }

        public Criteria andPhHighIsNull() {
            addCriterion("ph_high is null");
            return (Criteria) this;
        }

        public Criteria andPhHighIsNotNull() {
            addCriterion("ph_high is not null");
            return (Criteria) this;
        }

        public Criteria andPhHighEqualTo(Float value) {
            addCriterion("ph_high =", value, "phHigh");
            return (Criteria) this;
        }

        public Criteria andPhHighNotEqualTo(Float value) {
            addCriterion("ph_high <>", value, "phHigh");
            return (Criteria) this;
        }

        public Criteria andPhHighGreaterThan(Float value) {
            addCriterion("ph_high >", value, "phHigh");
            return (Criteria) this;
        }

        public Criteria andPhHighGreaterThanOrEqualTo(Float value) {
            addCriterion("ph_high >=", value, "phHigh");
            return (Criteria) this;
        }

        public Criteria andPhHighLessThan(Float value) {
            addCriterion("ph_high <", value, "phHigh");
            return (Criteria) this;
        }

        public Criteria andPhHighLessThanOrEqualTo(Float value) {
            addCriterion("ph_high <=", value, "phHigh");
            return (Criteria) this;
        }

        public Criteria andPhHighIn(List<Float> values) {
            addCriterion("ph_high in", values, "phHigh");
            return (Criteria) this;
        }

        public Criteria andPhHighNotIn(List<Float> values) {
            addCriterion("ph_high not in", values, "phHigh");
            return (Criteria) this;
        }

        public Criteria andPhHighBetween(Float value1, Float value2) {
            addCriterion("ph_high between", value1, value2, "phHigh");
            return (Criteria) this;
        }

        public Criteria andPhHighNotBetween(Float value1, Float value2) {
            addCriterion("ph_high not between", value1, value2, "phHigh");
            return (Criteria) this;
        }

        public Criteria andCrIsNull() {
            addCriterion("Cr is null");
            return (Criteria) this;
        }

        public Criteria andCrIsNotNull() {
            addCriterion("Cr is not null");
            return (Criteria) this;
        }

        public Criteria andCrEqualTo(Float value) {
            addCriterion("Cr =", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrNotEqualTo(Float value) {
            addCriterion("Cr <>", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrGreaterThan(Float value) {
            addCriterion("Cr >", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrGreaterThanOrEqualTo(Float value) {
            addCriterion("Cr >=", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrLessThan(Float value) {
            addCriterion("Cr <", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrLessThanOrEqualTo(Float value) {
            addCriterion("Cr <=", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrIn(List<Float> values) {
            addCriterion("Cr in", values, "cr");
            return (Criteria) this;
        }

        public Criteria andCrNotIn(List<Float> values) {
            addCriterion("Cr not in", values, "cr");
            return (Criteria) this;
        }

        public Criteria andCrBetween(Float value1, Float value2) {
            addCriterion("Cr between", value1, value2, "cr");
            return (Criteria) this;
        }

        public Criteria andCrNotBetween(Float value1, Float value2) {
            addCriterion("Cr not between", value1, value2, "cr");
            return (Criteria) this;
        }

        public Criteria andNiIsNull() {
            addCriterion("Ni is null");
            return (Criteria) this;
        }

        public Criteria andNiIsNotNull() {
            addCriterion("Ni is not null");
            return (Criteria) this;
        }

        public Criteria andNiEqualTo(Float value) {
            addCriterion("Ni =", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiNotEqualTo(Float value) {
            addCriterion("Ni <>", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiGreaterThan(Float value) {
            addCriterion("Ni >", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiGreaterThanOrEqualTo(Float value) {
            addCriterion("Ni >=", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiLessThan(Float value) {
            addCriterion("Ni <", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiLessThanOrEqualTo(Float value) {
            addCriterion("Ni <=", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiIn(List<Float> values) {
            addCriterion("Ni in", values, "ni");
            return (Criteria) this;
        }

        public Criteria andNiNotIn(List<Float> values) {
            addCriterion("Ni not in", values, "ni");
            return (Criteria) this;
        }

        public Criteria andNiBetween(Float value1, Float value2) {
            addCriterion("Ni between", value1, value2, "ni");
            return (Criteria) this;
        }

        public Criteria andNiNotBetween(Float value1, Float value2) {
            addCriterion("Ni not between", value1, value2, "ni");
            return (Criteria) this;
        }

        public Criteria andCuIsNull() {
            addCriterion("Cu is null");
            return (Criteria) this;
        }

        public Criteria andCuIsNotNull() {
            addCriterion("Cu is not null");
            return (Criteria) this;
        }

        public Criteria andCuEqualTo(Float value) {
            addCriterion("Cu =", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuNotEqualTo(Float value) {
            addCriterion("Cu <>", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuGreaterThan(Float value) {
            addCriterion("Cu >", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuGreaterThanOrEqualTo(Float value) {
            addCriterion("Cu >=", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuLessThan(Float value) {
            addCriterion("Cu <", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuLessThanOrEqualTo(Float value) {
            addCriterion("Cu <=", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuIn(List<Float> values) {
            addCriterion("Cu in", values, "cu");
            return (Criteria) this;
        }

        public Criteria andCuNotIn(List<Float> values) {
            addCriterion("Cu not in", values, "cu");
            return (Criteria) this;
        }

        public Criteria andCuBetween(Float value1, Float value2) {
            addCriterion("Cu between", value1, value2, "cu");
            return (Criteria) this;
        }

        public Criteria andCuNotBetween(Float value1, Float value2) {
            addCriterion("Cu not between", value1, value2, "cu");
            return (Criteria) this;
        }

        public Criteria andZnIsNull() {
            addCriterion("Zn is null");
            return (Criteria) this;
        }

        public Criteria andZnIsNotNull() {
            addCriterion("Zn is not null");
            return (Criteria) this;
        }

        public Criteria andZnEqualTo(Float value) {
            addCriterion("Zn =", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnNotEqualTo(Float value) {
            addCriterion("Zn <>", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnGreaterThan(Float value) {
            addCriterion("Zn >", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnGreaterThanOrEqualTo(Float value) {
            addCriterion("Zn >=", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnLessThan(Float value) {
            addCriterion("Zn <", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnLessThanOrEqualTo(Float value) {
            addCriterion("Zn <=", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnIn(List<Float> values) {
            addCriterion("Zn in", values, "zn");
            return (Criteria) this;
        }

        public Criteria andZnNotIn(List<Float> values) {
            addCriterion("Zn not in", values, "zn");
            return (Criteria) this;
        }

        public Criteria andZnBetween(Float value1, Float value2) {
            addCriterion("Zn between", value1, value2, "zn");
            return (Criteria) this;
        }

        public Criteria andZnNotBetween(Float value1, Float value2) {
            addCriterion("Zn not between", value1, value2, "zn");
            return (Criteria) this;
        }

        public Criteria andAsIsNull() {
            addCriterion("_As is null");
            return (Criteria) this;
        }

        public Criteria andAsIsNotNull() {
            addCriterion("_As is not null");
            return (Criteria) this;
        }

        public Criteria andAsEqualTo(Float value) {
            addCriterion("_As =", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsNotEqualTo(Float value) {
            addCriterion("_As <>", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsGreaterThan(Float value) {
            addCriterion("_As >", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsGreaterThanOrEqualTo(Float value) {
            addCriterion("_As >=", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsLessThan(Float value) {
            addCriterion("_As <", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsLessThanOrEqualTo(Float value) {
            addCriterion("_As <=", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsIn(List<Float> values) {
            addCriterion("_As in", values, "as");
            return (Criteria) this;
        }

        public Criteria andAsNotIn(List<Float> values) {
            addCriterion("_As not in", values, "as");
            return (Criteria) this;
        }

        public Criteria andAsBetween(Float value1, Float value2) {
            addCriterion("_As between", value1, value2, "as");
            return (Criteria) this;
        }

        public Criteria andAsNotBetween(Float value1, Float value2) {
            addCriterion("_As not between", value1, value2, "as");
            return (Criteria) this;
        }

        public Criteria andCdIsNull() {
            addCriterion("Cd is null");
            return (Criteria) this;
        }

        public Criteria andCdIsNotNull() {
            addCriterion("Cd is not null");
            return (Criteria) this;
        }

        public Criteria andCdEqualTo(Float value) {
            addCriterion("Cd =", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotEqualTo(Float value) {
            addCriterion("Cd <>", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThan(Float value) {
            addCriterion("Cd >", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThanOrEqualTo(Float value) {
            addCriterion("Cd >=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThan(Float value) {
            addCriterion("Cd <", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThanOrEqualTo(Float value) {
            addCriterion("Cd <=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdIn(List<Float> values) {
            addCriterion("Cd in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotIn(List<Float> values) {
            addCriterion("Cd not in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdBetween(Float value1, Float value2) {
            addCriterion("Cd between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotBetween(Float value1, Float value2) {
            addCriterion("Cd not between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andHgIsNull() {
            addCriterion("Hg is null");
            return (Criteria) this;
        }

        public Criteria andHgIsNotNull() {
            addCriterion("Hg is not null");
            return (Criteria) this;
        }

        public Criteria andHgEqualTo(Float value) {
            addCriterion("Hg =", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgNotEqualTo(Float value) {
            addCriterion("Hg <>", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgGreaterThan(Float value) {
            addCriterion("Hg >", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgGreaterThanOrEqualTo(Float value) {
            addCriterion("Hg >=", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgLessThan(Float value) {
            addCriterion("Hg <", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgLessThanOrEqualTo(Float value) {
            addCriterion("Hg <=", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgIn(List<Float> values) {
            addCriterion("Hg in", values, "hg");
            return (Criteria) this;
        }

        public Criteria andHgNotIn(List<Float> values) {
            addCriterion("Hg not in", values, "hg");
            return (Criteria) this;
        }

        public Criteria andHgBetween(Float value1, Float value2) {
            addCriterion("Hg between", value1, value2, "hg");
            return (Criteria) this;
        }

        public Criteria andHgNotBetween(Float value1, Float value2) {
            addCriterion("Hg not between", value1, value2, "hg");
            return (Criteria) this;
        }

        public Criteria andPbIsNull() {
            addCriterion("Pb is null");
            return (Criteria) this;
        }

        public Criteria andPbIsNotNull() {
            addCriterion("Pb is not null");
            return (Criteria) this;
        }

        public Criteria andPbEqualTo(Float value) {
            addCriterion("Pb =", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotEqualTo(Float value) {
            addCriterion("Pb <>", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbGreaterThan(Float value) {
            addCriterion("Pb >", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbGreaterThanOrEqualTo(Float value) {
            addCriterion("Pb >=", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbLessThan(Float value) {
            addCriterion("Pb <", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbLessThanOrEqualTo(Float value) {
            addCriterion("Pb <=", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbIn(List<Float> values) {
            addCriterion("Pb in", values, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotIn(List<Float> values) {
            addCriterion("Pb not in", values, "pb");
            return (Criteria) this;
        }

        public Criteria andPbBetween(Float value1, Float value2) {
            addCriterion("Pb between", value1, value2, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotBetween(Float value1, Float value2) {
            addCriterion("Pb not between", value1, value2, "pb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pollutionstandard
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pollutionstandard
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}