package com.dlut.pojo;

public class Sourcetable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable.pollutionName
     *
     * @mbggenerated
     */
    private String pollutionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable.Cr
     *
     * @mbggenerated
     */
    private Integer cr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable.Ni
     *
     * @mbggenerated
     */
    private Integer ni;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable.Cu
     *
     * @mbggenerated
     */
    private Integer cu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable.Zn
     *
     * @mbggenerated
     */
    private Integer zn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable._As
     *
     * @mbggenerated
     */
    private Integer as;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable.Cd
     *
     * @mbggenerated
     */
    private Integer cd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable.Hg
     *
     * @mbggenerated
     */
    private Integer hg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable.Pb
     *
     * @mbggenerated
     */
    private Integer pb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcetable._describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public Sourcetable(Integer id, String pollutionname, Integer cr, Integer ni, Integer cu, Integer zn, Integer as, Integer cd, Integer hg, Integer pb, String describe) {
        this.id = id;
        this.pollutionname = pollutionname;
        this.cr = cr;
        this.ni = ni;
        this.cu = cu;
        this.zn = zn;
        this.as = as;
        this.cd = cd;
        this.hg = hg;
        this.pb = pb;
        this.describe = describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable.id
     *
     * @return the value of sourcetable.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable.pollutionName
     *
     * @return the value of sourcetable.pollutionName
     *
     * @mbggenerated
     */
    public String getPollutionname() {
        return pollutionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable.Cr
     *
     * @return the value of sourcetable.Cr
     *
     * @mbggenerated
     */
    public Integer getCr() {
        return cr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable.Ni
     *
     * @return the value of sourcetable.Ni
     *
     * @mbggenerated
     */
    public Integer getNi() {
        return ni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable.Cu
     *
     * @return the value of sourcetable.Cu
     *
     * @mbggenerated
     */
    public Integer getCu() {
        return cu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable.Zn
     *
     * @return the value of sourcetable.Zn
     *
     * @mbggenerated
     */
    public Integer getZn() {
        return zn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable._As
     *
     * @return the value of sourcetable._As
     *
     * @mbggenerated
     */
    public Integer getAs() {
        return as;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable.Cd
     *
     * @return the value of sourcetable.Cd
     *
     * @mbggenerated
     */
    public Integer getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable.Hg
     *
     * @return the value of sourcetable.Hg
     *
     * @mbggenerated
     */
    public Integer getHg() {
        return hg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable.Pb
     *
     * @return the value of sourcetable.Pb
     *
     * @mbggenerated
     */
    public Integer getPb() {
        return pb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcetable._describe
     *
     * @return the value of sourcetable._describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }
}