package com.dlut.pojo;

import java.util.ArrayList;
import java.util.List;

public class SourcetableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public SourcetableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPollutionnameIsNull() {
            addCriterion("pollutionName is null");
            return (Criteria) this;
        }

        public Criteria andPollutionnameIsNotNull() {
            addCriterion("pollutionName is not null");
            return (Criteria) this;
        }

        public Criteria andPollutionnameEqualTo(String value) {
            addCriterion("pollutionName =", value, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameNotEqualTo(String value) {
            addCriterion("pollutionName <>", value, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameGreaterThan(String value) {
            addCriterion("pollutionName >", value, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameGreaterThanOrEqualTo(String value) {
            addCriterion("pollutionName >=", value, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameLessThan(String value) {
            addCriterion("pollutionName <", value, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameLessThanOrEqualTo(String value) {
            addCriterion("pollutionName <=", value, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameLike(String value) {
            addCriterion("pollutionName like", value, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameNotLike(String value) {
            addCriterion("pollutionName not like", value, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameIn(List<String> values) {
            addCriterion("pollutionName in", values, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameNotIn(List<String> values) {
            addCriterion("pollutionName not in", values, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameBetween(String value1, String value2) {
            addCriterion("pollutionName between", value1, value2, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andPollutionnameNotBetween(String value1, String value2) {
            addCriterion("pollutionName not between", value1, value2, "pollutionname");
            return (Criteria) this;
        }

        public Criteria andCrIsNull() {
            addCriterion("Cr is null");
            return (Criteria) this;
        }

        public Criteria andCrIsNotNull() {
            addCriterion("Cr is not null");
            return (Criteria) this;
        }

        public Criteria andCrEqualTo(Integer value) {
            addCriterion("Cr =", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrNotEqualTo(Integer value) {
            addCriterion("Cr <>", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrGreaterThan(Integer value) {
            addCriterion("Cr >", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrGreaterThanOrEqualTo(Integer value) {
            addCriterion("Cr >=", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrLessThan(Integer value) {
            addCriterion("Cr <", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrLessThanOrEqualTo(Integer value) {
            addCriterion("Cr <=", value, "cr");
            return (Criteria) this;
        }

        public Criteria andCrIn(List<Integer> values) {
            addCriterion("Cr in", values, "cr");
            return (Criteria) this;
        }

        public Criteria andCrNotIn(List<Integer> values) {
            addCriterion("Cr not in", values, "cr");
            return (Criteria) this;
        }

        public Criteria andCrBetween(Integer value1, Integer value2) {
            addCriterion("Cr between", value1, value2, "cr");
            return (Criteria) this;
        }

        public Criteria andCrNotBetween(Integer value1, Integer value2) {
            addCriterion("Cr not between", value1, value2, "cr");
            return (Criteria) this;
        }

        public Criteria andNiIsNull() {
            addCriterion("Ni is null");
            return (Criteria) this;
        }

        public Criteria andNiIsNotNull() {
            addCriterion("Ni is not null");
            return (Criteria) this;
        }

        public Criteria andNiEqualTo(Integer value) {
            addCriterion("Ni =", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiNotEqualTo(Integer value) {
            addCriterion("Ni <>", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiGreaterThan(Integer value) {
            addCriterion("Ni >", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiGreaterThanOrEqualTo(Integer value) {
            addCriterion("Ni >=", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiLessThan(Integer value) {
            addCriterion("Ni <", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiLessThanOrEqualTo(Integer value) {
            addCriterion("Ni <=", value, "ni");
            return (Criteria) this;
        }

        public Criteria andNiIn(List<Integer> values) {
            addCriterion("Ni in", values, "ni");
            return (Criteria) this;
        }

        public Criteria andNiNotIn(List<Integer> values) {
            addCriterion("Ni not in", values, "ni");
            return (Criteria) this;
        }

        public Criteria andNiBetween(Integer value1, Integer value2) {
            addCriterion("Ni between", value1, value2, "ni");
            return (Criteria) this;
        }

        public Criteria andNiNotBetween(Integer value1, Integer value2) {
            addCriterion("Ni not between", value1, value2, "ni");
            return (Criteria) this;
        }

        public Criteria andCuIsNull() {
            addCriterion("Cu is null");
            return (Criteria) this;
        }

        public Criteria andCuIsNotNull() {
            addCriterion("Cu is not null");
            return (Criteria) this;
        }

        public Criteria andCuEqualTo(Integer value) {
            addCriterion("Cu =", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuNotEqualTo(Integer value) {
            addCriterion("Cu <>", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuGreaterThan(Integer value) {
            addCriterion("Cu >", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuGreaterThanOrEqualTo(Integer value) {
            addCriterion("Cu >=", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuLessThan(Integer value) {
            addCriterion("Cu <", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuLessThanOrEqualTo(Integer value) {
            addCriterion("Cu <=", value, "cu");
            return (Criteria) this;
        }

        public Criteria andCuIn(List<Integer> values) {
            addCriterion("Cu in", values, "cu");
            return (Criteria) this;
        }

        public Criteria andCuNotIn(List<Integer> values) {
            addCriterion("Cu not in", values, "cu");
            return (Criteria) this;
        }

        public Criteria andCuBetween(Integer value1, Integer value2) {
            addCriterion("Cu between", value1, value2, "cu");
            return (Criteria) this;
        }

        public Criteria andCuNotBetween(Integer value1, Integer value2) {
            addCriterion("Cu not between", value1, value2, "cu");
            return (Criteria) this;
        }

        public Criteria andZnIsNull() {
            addCriterion("Zn is null");
            return (Criteria) this;
        }

        public Criteria andZnIsNotNull() {
            addCriterion("Zn is not null");
            return (Criteria) this;
        }

        public Criteria andZnEqualTo(Integer value) {
            addCriterion("Zn =", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnNotEqualTo(Integer value) {
            addCriterion("Zn <>", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnGreaterThan(Integer value) {
            addCriterion("Zn >", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnGreaterThanOrEqualTo(Integer value) {
            addCriterion("Zn >=", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnLessThan(Integer value) {
            addCriterion("Zn <", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnLessThanOrEqualTo(Integer value) {
            addCriterion("Zn <=", value, "zn");
            return (Criteria) this;
        }

        public Criteria andZnIn(List<Integer> values) {
            addCriterion("Zn in", values, "zn");
            return (Criteria) this;
        }

        public Criteria andZnNotIn(List<Integer> values) {
            addCriterion("Zn not in", values, "zn");
            return (Criteria) this;
        }

        public Criteria andZnBetween(Integer value1, Integer value2) {
            addCriterion("Zn between", value1, value2, "zn");
            return (Criteria) this;
        }

        public Criteria andZnNotBetween(Integer value1, Integer value2) {
            addCriterion("Zn not between", value1, value2, "zn");
            return (Criteria) this;
        }

        public Criteria andAsIsNull() {
            addCriterion("_As is null");
            return (Criteria) this;
        }

        public Criteria andAsIsNotNull() {
            addCriterion("_As is not null");
            return (Criteria) this;
        }

        public Criteria andAsEqualTo(Integer value) {
            addCriterion("_As =", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsNotEqualTo(Integer value) {
            addCriterion("_As <>", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsGreaterThan(Integer value) {
            addCriterion("_As >", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsGreaterThanOrEqualTo(Integer value) {
            addCriterion("_As >=", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsLessThan(Integer value) {
            addCriterion("_As <", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsLessThanOrEqualTo(Integer value) {
            addCriterion("_As <=", value, "as");
            return (Criteria) this;
        }

        public Criteria andAsIn(List<Integer> values) {
            addCriterion("_As in", values, "as");
            return (Criteria) this;
        }

        public Criteria andAsNotIn(List<Integer> values) {
            addCriterion("_As not in", values, "as");
            return (Criteria) this;
        }

        public Criteria andAsBetween(Integer value1, Integer value2) {
            addCriterion("_As between", value1, value2, "as");
            return (Criteria) this;
        }

        public Criteria andAsNotBetween(Integer value1, Integer value2) {
            addCriterion("_As not between", value1, value2, "as");
            return (Criteria) this;
        }

        public Criteria andCdIsNull() {
            addCriterion("Cd is null");
            return (Criteria) this;
        }

        public Criteria andCdIsNotNull() {
            addCriterion("Cd is not null");
            return (Criteria) this;
        }

        public Criteria andCdEqualTo(Integer value) {
            addCriterion("Cd =", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotEqualTo(Integer value) {
            addCriterion("Cd <>", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThan(Integer value) {
            addCriterion("Cd >", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Cd >=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThan(Integer value) {
            addCriterion("Cd <", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThanOrEqualTo(Integer value) {
            addCriterion("Cd <=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdIn(List<Integer> values) {
            addCriterion("Cd in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotIn(List<Integer> values) {
            addCriterion("Cd not in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdBetween(Integer value1, Integer value2) {
            addCriterion("Cd between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotBetween(Integer value1, Integer value2) {
            addCriterion("Cd not between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andHgIsNull() {
            addCriterion("Hg is null");
            return (Criteria) this;
        }

        public Criteria andHgIsNotNull() {
            addCriterion("Hg is not null");
            return (Criteria) this;
        }

        public Criteria andHgEqualTo(Integer value) {
            addCriterion("Hg =", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgNotEqualTo(Integer value) {
            addCriterion("Hg <>", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgGreaterThan(Integer value) {
            addCriterion("Hg >", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgGreaterThanOrEqualTo(Integer value) {
            addCriterion("Hg >=", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgLessThan(Integer value) {
            addCriterion("Hg <", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgLessThanOrEqualTo(Integer value) {
            addCriterion("Hg <=", value, "hg");
            return (Criteria) this;
        }

        public Criteria andHgIn(List<Integer> values) {
            addCriterion("Hg in", values, "hg");
            return (Criteria) this;
        }

        public Criteria andHgNotIn(List<Integer> values) {
            addCriterion("Hg not in", values, "hg");
            return (Criteria) this;
        }

        public Criteria andHgBetween(Integer value1, Integer value2) {
            addCriterion("Hg between", value1, value2, "hg");
            return (Criteria) this;
        }

        public Criteria andHgNotBetween(Integer value1, Integer value2) {
            addCriterion("Hg not between", value1, value2, "hg");
            return (Criteria) this;
        }

        public Criteria andPbIsNull() {
            addCriterion("Pb is null");
            return (Criteria) this;
        }

        public Criteria andPbIsNotNull() {
            addCriterion("Pb is not null");
            return (Criteria) this;
        }

        public Criteria andPbEqualTo(Integer value) {
            addCriterion("Pb =", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotEqualTo(Integer value) {
            addCriterion("Pb <>", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbGreaterThan(Integer value) {
            addCriterion("Pb >", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbGreaterThanOrEqualTo(Integer value) {
            addCriterion("Pb >=", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbLessThan(Integer value) {
            addCriterion("Pb <", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbLessThanOrEqualTo(Integer value) {
            addCriterion("Pb <=", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbIn(List<Integer> values) {
            addCriterion("Pb in", values, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotIn(List<Integer> values) {
            addCriterion("Pb not in", values, "pb");
            return (Criteria) this;
        }

        public Criteria andPbBetween(Integer value1, Integer value2) {
            addCriterion("Pb between", value1, value2, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotBetween(Integer value1, Integer value2) {
            addCriterion("Pb not between", value1, value2, "pb");
            return (Criteria) this;
        }

        public Criteria andDescribeIsNull() {
            addCriterion("_describe is null");
            return (Criteria) this;
        }

        public Criteria andDescribeIsNotNull() {
            addCriterion("_describe is not null");
            return (Criteria) this;
        }

        public Criteria andDescribeEqualTo(String value) {
            addCriterion("_describe =", value, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeNotEqualTo(String value) {
            addCriterion("_describe <>", value, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeGreaterThan(String value) {
            addCriterion("_describe >", value, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("_describe >=", value, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeLessThan(String value) {
            addCriterion("_describe <", value, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeLessThanOrEqualTo(String value) {
            addCriterion("_describe <=", value, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeLike(String value) {
            addCriterion("_describe like", value, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeNotLike(String value) {
            addCriterion("_describe not like", value, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeIn(List<String> values) {
            addCriterion("_describe in", values, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeNotIn(List<String> values) {
            addCriterion("_describe not in", values, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeBetween(String value1, String value2) {
            addCriterion("_describe between", value1, value2, "describe");
            return (Criteria) this;
        }

        public Criteria andDescribeNotBetween(String value1, String value2) {
            addCriterion("_describe not between", value1, value2, "describe");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sourcetable
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sourcetable
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}