package com.dlut.pojo;

public class Userfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.algo_name
     *
     * @mbggenerated
     */
    private String algoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.file_format
     *
     * @mbggenerated
     */
    private String fileFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.file_time
     *
     * @mbggenerated
     */
    private String fileTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.algo_id
     *
     * @mbggenerated
     */
    private Integer algoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfile
     *
     * @mbggenerated
     */
    public Userfile(Integer id, Integer userId, String userName, String algoName, String fileName, String fileFormat, String fileTime, Integer algoId) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.algoName = algoName;
        this.fileName = fileName;
        this.fileFormat = fileFormat;
        this.fileTime = fileTime;
        this.algoId = algoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.id
     *
     * @return the value of userfile.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.user_id
     *
     * @return the value of userfile.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.user_name
     *
     * @return the value of userfile.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.algo_name
     *
     * @return the value of userfile.algo_name
     *
     * @mbggenerated
     */
    public String getAlgoName() {
        return algoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.file_name
     *
     * @return the value of userfile.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.file_format
     *
     * @return the value of userfile.file_format
     *
     * @mbggenerated
     */
    public String getFileFormat() {
        return fileFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.file_time
     *
     * @return the value of userfile.file_time
     *
     * @mbggenerated
     */
    public String getFileTime() {
        return fileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.algo_id
     *
     * @return the value of userfile.algo_id
     *
     * @mbggenerated
     */
    public Integer getAlgoId() {
        return algoId;
    }
}